require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - app/views/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
