require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb

Layout/LineLength:
  Max: 120
  Exclude:
    - app/views/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
